site_name: "Brielle's Open Science Resources"
theme:
  name: material
  logo: images/logo.png  # Optional: add your logo if you have one
  favicon: images/favicon.ico  # Optional: add a favicon
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate

nav:
  - Home: index.md
  - About: about.md
  - Open Science Methods:
      - Creating a DMP: open-science/dmp.md
      - Creating Your Own Website: open-science/website.md

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.highlight
  
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight

# Repository URL (if you want to show a GitHub link)
repo_url: https://github.com/yourusername/your-repo-name
repo_name: "GitHub"
